services:
  sitespeed.io-server:
    image: sitespeedio/server:${SITESPEED_IO_SERVER_VERSION}
    environment:
      redis_host: keydb
      redis_port: 6379
      redis_password: ${KEYDB_PASSWORD}
      database_user: ${POSTGRES_USER}
      database_server: postgresql
      database_name: sitespeedio
      database_password: ${POSTGRES_PASSWORD}
      database_port: 5432
    ports:
      - "3000:3000"
    networks:
      - skynet
    depends_on:
      - keydb
      - postgresql
      - minio
  sitespeed.io-testrunner:
    image: sitespeedio/testrunner:${SITESPEED_IO_TESTRUNNER_VERSION}
    environment:
      redis_host: keydb
      redis_port: 6379
      redis_password: ${KEYDB_PASSWORD}
      docker_extraparameters: '--cap-add=NET_ADMIN --network=skynet'
      sitespeed.io_s3_endpoint: "http://minio:9000" 
      sitespeed.io_s3_bucketname: 'sitespeedio'
      sitespeed.io_s3_key: 'sitespeedio'
      sitespeed.io_s3_secret:  "tracksofmytears"
      sitespeed.io_s3_region: "motown"
      sitespeed.io_s3_options_forcePathStyle: true
      sitespeed.io_s3_removeLocalResult: true
      sitespeed.io_resultBaseURL: ${RESULT_BASE_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    cap_add:
      - NET_ADMIN
    depends_on:
      - keydb
      - minio
      - sitespeed.io-server
    networks:
      - skynet